// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLbf3i2uPCAAlixK7EfnssLFkaIyT8wV8',
    appId: '1:800458721082:web:f33e079fd3461c6f013203',
    messagingSenderId: '800458721082',
    projectId: 'financetracker-finaldemo',
    authDomain: 'financetracker-finaldemo.firebaseapp.com',
    storageBucket: 'financetracker-finaldemo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqMhgfow9B4UDjg96MCIrAyoYG-31YTnk',
    appId: '1:800458721082:android:258b2e281c80c1f5013203',
    messagingSenderId: '800458721082',
    projectId: 'financetracker-finaldemo',
    storageBucket: 'financetracker-finaldemo.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLbf3i2uPCAAlixK7EfnssLFkaIyT8wV8',
    appId: '1:800458721082:web:13bf2c7920d1dfe2013203',
    messagingSenderId: '800458721082',
    projectId: 'financetracker-finaldemo',
    authDomain: 'financetracker-finaldemo.firebaseapp.com',
    storageBucket: 'financetracker-finaldemo.firebasestorage.app',
  );
}
